sudo: required
services:
  - docker

before_install:
  - docker build -t xbnrxout/udemy_docker_kubernetes -f dockerfile.dev .

script:
  - docker run -e CI=true xbnrxout/udemy_docker_kubernetes npm run test
#language: generic
#